[program:wedding-app-queue]
command=php /var/www/wedding-app/artisan queue:work redis --tries=3 --timeout=300 --sleep=3 --queue=default
directory=/var/www/wedding-app
autostart=true
autorestart=true
user=kriegar
redirect_stderr=true
stdout_logfile=/var/log/wedding-app-queue.log
stopwaitsecs=300
