// Mirrors App\Support\Currencies (PHP). Country list maps 1:1 to the backend's
// COUNTRY_CURRENCY keys so a country always resolves to a default currency.

export const COUNTRIES: { code: string; name: string }[] = [
    { code: 'US', name: 'United States' },
    { code: 'CA', name: 'Canada' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'IE', name: 'Ireland' },
    { code: 'AU', name: 'Australia' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'FR', name: 'France' },
    { code: 'DE', name: 'Germany' },
    { code: 'ES', name: 'Spain' },
    { code: 'IT', name: 'Italy' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'BE', name: 'Belgium' },
    { code: 'AT', name: 'Austria' },
    { code: 'PT', name: 'Portugal' },
    { code: 'FI', name: 'Finland' },
    { code: 'GR', name: 'Greece' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'SE', name: 'Sweden' },
    { code: 'NO', name: 'Norway' },
    { code: 'DK', name: 'Denmark' },
    { code: 'PL', name: 'Poland' },
    { code: 'CZ', name: 'Czechia' },
    { code: 'HU', name: 'Hungary' },
    { code: 'RO', name: 'Romania' },
    { code: 'JP', name: 'Japan' },
    { code: 'CN', name: 'China' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'SG', name: 'Singapore' },
    { code: 'IN', name: 'India' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'TH', name: 'Thailand' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'PH', name: 'Philippines' },
    { code: 'KR', name: 'South Korea' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'IL', name: 'Israel' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'MX', name: 'Mexico' },
    { code: 'BR', name: 'Brazil' },
    { code: 'AR', name: 'Argentina' },
    { code: 'CL', name: 'Chile' },
    { code: 'CO', name: 'Colombia' },
];

export const CURRENCIES: { code: string; label: string }[] = [
    { code: 'usd', label: 'USD — US Dollar' },
    { code: 'eur', label: 'EUR — Euro' },
    { code: 'gbp', label: 'GBP — British Pound' },
    { code: 'cad', label: 'CAD — Canadian Dollar' },
    { code: 'aud', label: 'AUD — Australian Dollar' },
    { code: 'nzd', label: 'NZD — New Zealand Dollar' },
    { code: 'chf', label: 'CHF — Swiss Franc' },
    { code: 'sek', label: 'SEK — Swedish Krona' },
    { code: 'nok', label: 'NOK — Norwegian Krone' },
    { code: 'dkk', label: 'DKK — Danish Krone' },
    { code: 'pln', label: 'PLN — Polish Złoty' },
    { code: 'czk', label: 'CZK — Czech Koruna' },
    { code: 'huf', label: 'HUF — Hungarian Forint' },
    { code: 'ron', label: 'RON — Romanian Leu' },
    { code: 'jpy', label: 'JPY — Japanese Yen' },
    { code: 'cny', label: 'CNY — Chinese Yuan' },
    { code: 'hkd', label: 'HKD — Hong Kong Dollar' },
    { code: 'sgd', label: 'SGD — Singapore Dollar' },
    { code: 'inr', label: 'INR — Indian Rupee' },
    { code: 'myr', label: 'MYR — Malaysian Ringgit' },
    { code: 'thb', label: 'THB — Thai Baht' },
    { code: 'idr', label: 'IDR — Indonesian Rupiah' },
    { code: 'php', label: 'PHP — Philippine Peso' },
    { code: 'krw', label: 'KRW — South Korean Won' },
    { code: 'aed', label: 'AED — UAE Dirham' },
    { code: 'sar', label: 'SAR — Saudi Riyal' },
    { code: 'ils', label: 'ILS — Israeli Shekel' },
    { code: 'zar', label: 'ZAR — South African Rand' },
    { code: 'mxn', label: 'MXN — Mexican Peso' },
    { code: 'brl', label: 'BRL — Brazilian Real' },
    { code: 'ars', label: 'ARS — Argentine Peso' },
    { code: 'clp', label: 'CLP — Chilean Peso' },
    { code: 'cop', label: 'COP — Colombian Peso' },
];
